spring:
  datasource:
    hikari:
      maximum-pool-size: 10
    url: "jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:15432}/${DB_NAME:default}?schema=default"
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driverClassName: "org.postgresql.Driver"
  liquibase:
    enabled: true
    changeLog: /db/changelog/db.changelog-master.xml
    parameters:
      log-level: FINE
  docker:
    compose:
      file: ./compose.yaml
  jpa:
    show-sql: true
    properties:
      hibernate:
        show_sql: false
  jackson:
    default-property-inclusion: NON_NULL
  security:
    user:
      name: user
      password: boilerUser123!

resilience4j:
  bulkhead:
    instances:
      orderDatabase: # 벌크헤드 이름
        maxConcurrentCalls: 10 # 동시에 허용할 최대 호출 수 (세마포어 개수)
        maxWaitDuration: 300ms # 진입을 위해 기다릴 최대 시간 (초과 시 에러)